### ISSUE TITLE
Circular dependency causes errors on linux

### ISSUE THREAD

**Issue by NickStafford2** [JarvisCapstone/Syllahub#37]
I hoped this wouldn't happen. It is caused by line 10 in  /app/auth/routes.py
from app.syllabus.forms import ApproveForm
this is a circular dependency. 

Here is the error from /var/log/httpd/error_log
[Tue Apr 30 23:12:39.633339 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742] mod_wsgi (pid=23288): Failed to exec Python script file '/var/www/html/syllahub.wsgi'.
[Tue Apr 30 23:12:39.633382 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742] mod_wsgi (pid=23288): Exception occurred processing WSGI script '/var/www/html/syllahub.wsgi'.
[Tue Apr 30 23:12:39.633881 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742] Traceback (most recent call last):
[Tue Apr 30 23:12:39.633915 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]   File "/var/www/html/syllahub.wsgi", line 15, in <module>
[Tue Apr 30 23:12:39.633918 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]     application = create_app(Config)
[Tue Apr 30 23:12:39.633921 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]   File "/var/www/html/app/__init__.py", line 36, in create_app
[Tue Apr 30 23:12:39.633923 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]     from app.auth import bp as auth_bp
[Tue Apr 30 23:12:39.633926 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]   File "/var/www/html/app/auth/__init__.py", line 5, in <module>
[Tue Apr 30 23:12:39.633928 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]     from app.auth import routes
[Tue Apr 30 23:12:39.633930 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]   File "/var/www/html/app/auth/routes.py", line 10, in <module>
[Tue Apr 30 23:12:39.633932 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]     from app.syllabus.forms import ApproveForm
[Tue Apr 30 23:12:39.633935 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]   File "/var/www/html/app/syllabus/__init__.py", line 6, in <module>
[Tue Apr 30 23:12:39.633937 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]     from app.syllabus import routes
[Tue Apr 30 23:12:39.633939 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]   File "/var/www/html/app/syllabus/routes.py", line 9, in <module>
[Tue Apr 30 23:12:39.633941 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]     from app.factory.factory import SyllabusFactory
[Tue Apr 30 23:12:39.633944 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]   File "/var/www/html/app/factory/__init__.py", line 6, in <module>
[Tue Apr 30 23:12:39.633946 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]     from app.factory import routes
[Tue Apr 30 23:12:39.633948 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]   File "/var/www/html/app/factory/routes.py", line 8, in <module>
[Tue Apr 30 23:12:39.633950 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742]     from app.auth.routes import admin_required
[Tue Apr 30 23:12:39.633959 2019] [wsgi:error] [pid 23288:tid 139895632414464] [remote 107.10.238.235:56742] ImportError: cannot import name 'admin_required' from 'app.auth.routes' (/var/www/html/app/auth/routes.py)

**Comment by NickStafford2** [comment]
I removed the circular dependancy. the button didn't work anyway
